### ISSUE TITLE
some problems in track.py

### ISSUE THREAD

**Issue by LiYQi** [Gsak3l/Sports-Analysis-Software#10]
![image](https://github.com/Gsak3l/Sports-Analysis-Software/assets/114284920/66e7262d-22ee-411b-9a58-e82f31a28d24)
Thank you very much for your work, I have been learning your project recently and it has helped me a lot. But when I uploaded the video to generate the tracking result, an error occurred and it showed an error in the opt.image_ parameter, so I would like to ask if there is an error in the track.py? I will be very thankful if you can answer my question!

**Comment by Gsak3l** [comment]
Sorry for the late response. It should be fixed now on the no-db branch.
