### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by russskiykorablidinah** [Gsak3l/Sports-Analysis-Software#3]
Hello.
Can you tell me if there are instructions for use?

**Comment by Gsak3l** [comment]
>  Can you tell me if there are instructions for use?

I will be updating the readme soon but for now follow these steps on your terminal:
```
git clone https://github.com/Gsak3l/Sports-Analysis-Software.git
cd Sports-Analysis-Software
pip install -r requirements.txt
python main.py
```
I retrained YoloV5 to be able to recognize players from a local team, therefore you may need to retrain the algorithm to suit your needs.

You can test the already trained set with [this video](https://www.youtube.com/watch?v=l881pUdNU2Y) (you can download the video directly from the app).
